name = "ProximalCore"
uuid = "dc4f5ac2-75d1-4f31-931e-60435d74994b"
authors = ["Lorenzo Stella <lorenzostella@gmail.com>"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.2"
julia = "1.2"
